[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = false

[[language]]
name = "json"
formatter = { command = 'prettier', args = ['invoke'] }
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = false

[[language]]
name = "css"
formatter = { command = 'prettier', args = ['invoke'] }
formatter = { command = 'prettier', args = ["--parser", "css"] }
auto-format = false

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = false

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = false

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = false

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = false
