# history = 10000
import = ["/home/rencedm112/.config/alacritty/themes/dracula.toml"]
# multiplier = 3

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations_theme_variant = "Dark"
dynamic_title = true
opacity = 0.8
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
